---
# handlers file for kube-apiserver
- name: start kube-apiserver
  become: yes
  service:
    name: apiserver
    state: started

- name: restart kube-apiserver
  become: yes
  service:
    name: apiserver
    state: restarted
