---
# handlers file for kube-master
- name: start kubelet
  become: yes
  service:
    name: kubelet
    state: started

- name: restart kubelet
  become: yes
  service:
    name: kubelet
    state: restarted

- name: restart calico-node
  become: yes
  service:
    name: calico-node
    state: restarted
