# provider is set in the inventory
- include_vars: "{{ item }}"
  with_first_found:
   - "{{ provider }}.yml"
   - "default.yml"

- name: create kubernetes dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ kubernetes_config_dir }}"
    - "{{ kubernetes_cni_dir }}"
  become: yes
  tags:
    - kube-worker

# kubelet-wrapper is only available on CoreOS 962.0.0+ so we make sure its here
# to ensure backwards compatability.
# See https://coreos.com/kubernetes/docs/latest/kubelet-wrapper.htm
#- name: create kubernetes /opt/bin
#  file:
#    path: "{{ item }}"
#    state: directory
#    mode: 0755
#    recurse: yes
#  with_items:
#    - "/opt/bin"
#  become: yes
#  tags:
#    - kube-worker

- name: download kubelet-wrapper
  become: yes
  get_url:
    url: "{{ kubernetes_kubelet_wrapper }}"
    dest: /opt/bin/kubelet-wrapper
    mode: 0775
  tags:
    - kube-worker

# worker
- name: deploy kubelet service
  become: yes
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
  notify:
    - reload systemd
    - restart kubelet
  tags:
    - kube-worker

- name: ensure kubelet is running
  become: yes
  service:
    name: kubelet
    state: started
    enabled: yes
  tags:
    - kube-worker

- name: deploy kube-worker manifests
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: worker-kubeconfig.j2
      dest: "{{ kubernetes_config_dir }}/worker-kubeconfig"
    - src: kube-proxy.yaml.j2
      dest: "{{ kubernetes_manifest_dir }}/kube-proxy.yaml"
    - src: "10-{{ network_plugin }}.conf.j2"
      dest: "{{ kubernetes_cni_dir }}/10-{{ network_plugin }}.conf"
  tags:
    - kube-worker

- include: calico.yml
  tags:
    - calico
    - kube-worker
